name: Test Maven Setup (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  test-maven:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Display environment information
      run: |
        echo "PATH: $PATH"
        echo "JAVA_HOME: $JAVA_HOME"
        echo "M2_HOME: $M2_HOME"
        ls -l $JAVA_HOME
        which java
        which mvn
        
    - name: Check Maven version
      run: mvn --version

    - name: Run simple Maven command
      run: mvn help:evaluate -Dexpression=maven.version -q -DforceStdout
