name: Test Maven Setup (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  test-maven:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Check Maven version
      run: mvn --version

    - name: Run simple Maven command
      run: mvn help:evaluate -Dexpression=maven.version -q -DforceStdout
